### ISSUE TITLE
Error running `python -c "import fewshot; fewshot.make_challenge('flex');"`

### ISSUE THREAD

**Issue by MicPie** [allenai/flex#3]
Hello,

thank you very much for making the FLEX code available.

I installed it according to https://github.com/allenai/flex#installation (running `pip install -e .` in the flex dir) and tried to run `python -c "import fewshot; fewshot.make_challenge('flex');"` but I get the following error on Ubuntu and MacOSX:

```
Using custom data configuration flex-ead21b2c6fc7f994
Downloading and preparing dataset flex_challenge/flex to /home/mmp/.cache/huggingface/datasets/flex_challenge/flex-ead21b2c6fc7f994/0.0.1/e5706
b643506c30eaea9d75cf6d7cccccd7b2a87583e02892efab5b10291f493...
Generating test split: 0 examples [00:00, ? examples/s]Using custom data configuration newsgroupbao-255d26ad5737e61d
Downloading and preparing dataset flex/newsgroupbao to .cache/huggingface/datasets/flex/newsgroupbao-255d26ad5737e61d/0.0.1/4d8971995
32a37859555f12a74cee1cabc88d46d86afafa9cecbedfd2cf992b5...
Traceback (most recent call last):
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 86, in _call_target
    return _target_(*args, **kwargs)
  File "flex/fewshot/datasets/store.py", line 73, in __init__
    self.store = load_dataset(**hf_load_kwargs)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 1691, in load_dataset
    builder_instance.download_and_prepare(                                                                                                       File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 605, in download_and_prepare
    self._download_and_prepare(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 1104, in _download_and_prepare
    super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 694, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 1087, in _prepare_split
    for key, record in logging.tqdm(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File ".cache/huggingface/modules/datasets_modules/datasets/flex/4d897199532a37859555f12a74cee1cabc88d46d86afafa9cecbedfd2cf992b5/fl
ex.py", line 154, in _generate_examples
    dataset = datasets.load_dataset(**load_dataset_kwargs)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 1664, in load_dataset
    builder_instance = load_dataset_builder(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 1516, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 1031, in __init__
    super().__init__(*args, **kwargs)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 265, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 375, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig NewsgroupConfig(name='18828_sci.space', version=3.0.0, data_dir=None, data_files=None, description='does not include
cross-posts and includes only the "From" and "Subject" headers.') doesn't have a 'script_version' key.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "flex/fewshot/challenges/registration.py", line 13, in make
    return registry.make(id, **evaluator_kwargs)
  File "flex/fewshot/challenges/registration.py", line 108, in make
    return self.get_spec(id).make(**evaluator_kwargs)
  File "flex/fewshot/challenges/registration.py", line 29, in make
    return Evaluator(config_name=self.id, hash=self.hash, **evaluator_kwargs)
  File "flex/fewshot/challenges/eval.py", line 89, in __init__
    self.dataset = load_dataset(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 1691, in load_dataset
    builder_instance.download_and_prepare(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 605, in download_and_prepare
    self._download_and_prepare(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 1104, in _download_and_prepare
    super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 694, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 1087, in _prepare_split
    for key, record in logging.tqdm(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File ".cache/huggingface/modules/datasets_modules/datasets/challenge/e5706b643506c30eaea9d75cf6d7cccccd7b2a87583e02892efab5b10291f4
93/challenge.py", line 109, in _generate_examples
    sampler = instantiate(challenge.metadatasampler)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 326, in instantiate_node
    value = instantiate_node(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 304, in instantiate_node
    items = [
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 305, in <listcomp>
    instantiate_node(item, convert=convert, recursive=recursive)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 326, in instantiate_node
    value = instantiate_node(
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 331, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "miniconda3/envs/flex/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 91, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'fewshot.datasets.store.Store':
ValueError('BuilderConfig NewsgroupConfig(name=\'18828_sci.space\', version=3.0.0, data_dir=None, data_files=None, description=\'does not inclu
de cross-posts and includes only the "From" and "Subject" headers.\') doesn\'t have a \'script_version\' key.')
full_key: datasets[0].labeled_store
```
I'm trying to track down the error but any help is highly appreciated. :-)

**Comment by MicPie** [comment]
Ok, I seem to have a fix.
The problem was that the outlined installation process didn't installed the versions from the `requirements.txt`.
Therefore, I run `pip install -r requirements.txt` before the `pip install -e .` which solved the issue.

**Comment by jbragg** [comment]
Thanks @MicPie I've added this to the instructions
