### ISSUE TITLE
python -c "import fewshot; fewshot.make_challenge('flex');"  Unable to download

### ISSUE THREAD

**Issue by ppzhr** [allenai/flex#7]
Error message：
Downloading and preparing dataset flex_challenge/flex (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /home/zhr/.cache/huggingface/datasets/flex_challenge/flex-ebe90660aa525d14/0.0.1/e5706b643506c30eaea9d75cf6d7cccccd7b2a87583e02892efab5b10291f493...
HF google storage unreachable. Downloading and preparing it from source
0 examples [00:00, ? examples/s]Downloading and preparing dataset flex/fewrelbao (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /home/zhr/.cache/huggingface/datasets/flex/fewrelbao/0.0.1/4d897199532a37859555f12a74cee1cabc88d46d86afafa9cecbedfd2cf992b5...
HF google storage unreachable. Downloading and preparing it from source
Traceback (most recent call last):
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 652, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/builder.py", line 986, in _prepare_split
    for key, record in utils.tqdm(
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/home/zhr/.cache/huggingface/modules/datasets_modules/datasets/flex/4d897199532a37859555f12a74cee1cabc88d46d86afafa9cecbedfd2cf992b5/flex.py", line 171, in _generate_examples
    dataset = datasets.load_dataset(**load_dataset_kwargs)
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 708, in load_dataset
    module_path, hash, resolved_file_path = prepare_module(
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/load.py", line 320, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 281, in cached_path
    output_path = get_from_cache(
  File "/home/zhr/anaconda3/envs/flex/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 623, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.5.0/datasets/few_rel/few_rel.py

**Comment by jbragg** [comment]
That URL is reachable for me https://raw.githubusercontent.com/huggingface/datasets/1.5.0/datasets/few_rel/few_rel.py
